id: mohw.tw.twha
canonical: https://twcore.mohw.gov.tw/ig/twha
name: TWHAIG
title: 臺灣健康檢查資料交換實作指引 (Taiwan Health Assessment Implementation Guide, TWHA IG)
description: 建立一般健康檢查、勞工健康檢查及成人預防保健之 FHIR 資料交換標準。繼承臺灣核心實作指引 (TW Core IG)。
status: active
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: STU1
publisher:
  name: 衛生福利部次世代數位醫療平臺專案辦公室 & 長庚醫療財團法人長庚紀念醫院
  url: https://twcore.mohw.gov.tw/twregistry/
contact:
  - name: 衛生福利部次世代數位醫療平臺專案辦公室
    telecom:
      - system: url
        value: https://twcore.mohw.gov.tw/twregistry/
dependencies:
  tw.gov.mohw.twcore: 1.0.0

parameters:
  special-url:
    - https://hapi.fhir.tw/fhir/CodeSystem/sf-BetNutChewAmount-codesystem
    - https://hapi.fhir.tw/fhir/CodeSystem/sf-BetNutChewBeh-codesystem
    - https://hapi.fhir.tw/fhir/CodeSystem/sf-BetNutChewQuit-codesystem
    - https://hapi.fhir.tw/fhir/CodeSystem/sf-BetNutChewYear-codesystem
    - https://hapi.fhir.tw/fhir/CodeSystem/sf-ObserBeh-codesystem
    - https://hapi.fhir.tw/fhir/ValueSet/sf-BetNutChewAmount-valueset
    - https://hapi.fhir.tw/fhir/ValueSet/sf-BetNutChewBeh-valueset
    - https://hapi.fhir.tw/fhir/ValueSet/sf-BetNutChewQuit-valueset
    - https://hapi.fhir.tw/fhir/ValueSet/sf-BetNutChewYear-valueset
  no-validate:
    - https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-CoreDataset
    - https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-ExtendedDataset
    - https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-PulmonaryFunction
    - https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-TWHAVitalSigns
    - https://twcore.mohw.gov.tw/ig/twha/ValueSet/VS-UnfitDiseases

menu:
  首頁 (Home): index.html
  背景與案例 (Background & Use Cases):
    背景 (Background): background.html
    應用案例 (Use Cases): usecases.html
  資料模型 (Data Model): datamodel.html
  檢查與紀錄定義 (Examinations):
    一般健康檢查 (General Exam): general-exam.html
    特殊危害健康作業 (Special Exam): special-exam.html
    成人預防保健 (Adult Preventive Care): adult-preventive-care.html
    勞工健康服務執行紀錄 (Service Record): service-record.html
    健康管理分級 (Health Management): health-management.html
  FHIR 資源 (FHIR Artifacts):
    資源總覽 (Artifacts Summary): artifacts.html
    Profiles: artifacts.html#1
    Extensions: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4
  術語與安全 (Terminology & Security):
    術語定義 (Terminology): terminology.html
    安全性考量 (Security): security.html
  下載區 (Downloads): downloads.html

